"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarDays, FilePlus2, Search } from "lucide-react";

type Payment = { id: number; client: string; service: string; expectedAmount: number; dueDate: string; status: string };
const rupees = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(amount);
const status = (value: string) => value.split("_").map((item) => item[0] + item.slice(1).toLowerCase()).join(" ");

export default function MonthlyBillingPage() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [query, setQuery] = useState("");
  const [payments, setPayments] = useState<Payment[]>([]);
  const [message, setMessage] = useState("Loading monthly invoices…");
  useEffect(() => { fetch("/api/payments").then((response) => response.json()).then((rows) => { if (Array.isArray(rows)) { setPayments(rows); setMessage("Monthly invoice ledger ready."); } else setMessage("Connect Google Sheets to load live invoices."); }).catch(() => setMessage("Invoice data is unavailable.")); }, []);
  const monthlyPayments = useMemo(() => payments.filter((payment) => payment.dueDate.startsWith(month) && payment.client.toLowerCase().includes(query.toLowerCase())), [month, payments, query]);
  const total = monthlyPayments.reduce((sum, payment) => sum + payment.expectedAmount, 0);
  const saveDraft = (event: FormEvent) => { event.preventDefault(); setMessage("Google Sheet connection is required before a live invoice can be saved."); };
  return <main className="min-h-screen bg-slate-100 p-5 text-slate-900 sm:p-8"><div className="mx-auto max-w-7xl">
    <header className="rounded-3xl bg-slate-950 px-6 py-7 text-white sm:px-8"><div className="flex items-center gap-3 text-amber-300"><CalendarDays className="h-5 w-5" /><span className="text-sm font-semibold tracking-widest">ARKA MONTHLY BILLING</span></div><h1 className="mt-4 text-3xl font-bold sm:text-4xl">Create and track each month’s invoices</h1><p className="mt-3 max-w-2xl text-base leading-7 text-slate-300">Add invoices to your Google Sheet, then follow their due dates, balances, and payment status here.</p></header>
    <div className="mt-5 flex flex-col gap-3 rounded-2xl border bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-medium text-emerald-800">{message}</p><div className="flex flex-wrap gap-3"><label className="text-sm font-medium">Billing month <input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="ml-2 rounded-lg border px-2 py-1.5" /></label><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="rounded-lg border py-1.5 pl-9 pr-3 text-sm" placeholder="Search client" /></label></div></div>
    <section className="mt-5 grid gap-5 xl:grid-cols-[.9fr_1.4fr]"><form onSubmit={saveDraft} className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><FilePlus2 className="h-5 w-5 text-amber-700" /><h2 className="text-xl font-bold">New monthly invoice</h2></div><p className="mt-2 text-sm leading-6 text-slate-600">This creates one invoice row for the chosen month after the Google Sheet is connected.</p><div className="mt-5 grid gap-3"><Field label="Client name" required /><Field label="Service" required /><div className="grid grid-cols-2 gap-3"><Field label="Invoice number" /><Field label="Amount" type="number" required /></div><div className="grid grid-cols-2 gap-3"><Field label="Invoice date" type="date" /><Field label="Due date" type="date" required /></div><label className="grid gap-1 text-sm font-medium">Billing cycle<select className="rounded-lg border px-3 py-2"><option>Monthly</option><option>One time</option><option>Quarterly</option></select></label></div><button className="mt-5 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Save monthly invoice</button></form>
      <div className="overflow-hidden rounded-2xl border bg-white"><div className="border-b px-5 py-4"><h2 className="font-bold">Invoice ledger</h2><p className="mt-1 text-sm text-slate-600">{monthlyPayments.length} invoice{monthlyPayments.length === 1 ? "" : "s"} · {rupees(total)}</p></div>{monthlyPayments.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Client</th><th>Service</th><th>Amount</th><th>Due date</th><th className="pr-5">Status</th></tr></thead><tbody>{monthlyPayments.map((payment) => <tr key={payment.id} className="border-t"><td className="px-5 py-4 font-semibold">{payment.client}</td><td>{payment.service}</td><td>{rupees(payment.expectedAmount)}</td><td>{payment.dueDate}</td><td className="pr-5">{status(payment.status)}</td></tr>)}</tbody></table></div> : <div className="p-12 text-center text-sm text-slate-600">No invoices loaded for this month.</div>}</div></section>
    <section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">Google Sheet structure</h2><p className="mt-2 text-sm leading-6 text-amber-950">Use one row per invoice. Required columns are Client Name, Service, Amount, and Due Date. Optional columns are Contact Person, Phone, Email, Billing Type, Billing From, Billing To, and Payment Reference. Keep the same headings in each monthly tab.</p></section>
  </div></main>;
}

function Field({ label, type = "text", required = false }: { label: string; type?: string; required?: boolean }) { return <label className="grid gap-1 text-sm font-medium">{label}<input type={type} required={required} className="rounded-lg border px-3 py-2" /></label>; }
