import { describe, expect, it, vi } from "vitest";
import { canTransition, deriveDateStatus } from "@/lib/payment-state";
import { normalizeSheetRow } from "@/lib/sheet-import";
import { reconcile } from "@/lib/reconciliation";
import { LocalStorageProvider } from "@/lib/storage";
import { demoModeEnabled,demoPayments } from "@/lib/demo-mode";
import { paymentLifecycle } from "@/lib/payment-lifecycle";
import { reminderEligibility } from "@/lib/reminder-eligibility";
import { EmailReminderProvider } from "@/lib/reminder-delivery";
import { DemoPaymentProofExtractionProvider } from "@/lib/payment-proof-extraction";

describe("payment state machine",()=>{
  it("allows proof upload but never turns proof upload into paid",()=>{expect(canTransition("OVERDUE","PROOF_UPLOADED")).toBe(true);expect(canTransition("OVERDUE","PAID")).toBe(false);expect(canTransition("PROOF_UPLOADED","PAID")).toBe(false);});
  it("derives date statuses",()=>{expect(deriveDateStatus("2026-09-16",new Date("2026-09-17T08:00:00+05:30"))).toBe("OVERDUE");});
});
describe("sheet import",()=>{
  it("normalizes a valid row",()=>{const result=normalizeSheetRow({"Client Name":"Acme","Service":"Retainer",Amount:"₹1,250.00","Due Date":"2026-10-01","Payment Reference":"acme-oct"},2);expect(result.errors).toEqual([]);expect(result.value?.amount).toBe(1250);expect(result.value?.reference).toBe("acme-oct");});
  it("rejects invalid records before sync",()=>{const result=normalizeSheetRow({"Client Name":"","Service":"","Amount":"0","Due Date":"not a date"},3);expect(result.errors).toHaveLength(4);});
});
describe("reconciliation",()=>{it("routes mismatches to review rather than paid",()=>{expect(reconcile({amount:100,dueDate:"2026-10-01"},{amount:90,date:null,transactionId:null,utr:null,confidence:0.99,status:"SUCCESS"}).result).toBe("MISMATCH");});});
describe("smart payment verification",()=>{
  it("requires identifiers and a confident amount before a match",()=>{expect(reconcile({amount:18000,dueDate:"2026-10-01",client:"UrbanNest"},{amount:null,date:null,transactionId:null,utr:null,confidence:0.99,status:"SUCCESS"}).result).toBe("MANUAL_REVIEW");expect(reconcile({amount:18000,dueDate:"2026-10-01"},{amount:18000,date:null,transactionId:null,utr:null,confidence:0.99,status:"SUCCESS"}).result).toBe("MANUAL_REVIEW");});
  it("uses deterministic extraction only in development demo mode",async()=>{vi.stubEnv("NODE_ENV","development");vi.stubEnv("DEMO_MODE","true");vi.stubEnv("DATABASE_URL","");const details=await new DemoPaymentProofExtractionProvider().extractPaymentDetails({paymentId:-2});expect(details.utr).toBe("DEMO-UTR-18000");vi.stubEnv("NODE_ENV","production");await expect(new DemoPaymentProofExtractionProvider().extractPaymentDetails({paymentId:-2})).rejects.toThrow("OCR_PROVIDER_NOT_CONFIGURED");vi.unstubAllEnvs();});
  it("never permits proof upload or OCR to skip human approval",()=>{expect(canTransition("PROOF_UPLOADED","PAID")).toBe(false);expect(canTransition("VERIFYING","PAID")).toBe(false);expect(canTransition("VERIFIED","PAID")).toBe(true);});
});
describe("private local storage",()=>{it("stores and retrieves a file without a public URL",async()=>{const storage=new LocalStorageProvider();await storage.put("payments/1/test",new TextEncoder().encode("proof").buffer,"image/png");const result=await storage.get("payments/1/test");expect(result.contentType).toBe("image/png");expect(result.key).toBe("payments/1/test");});});
describe("development demo mode",()=>{it("only exposes exactly two non-persistent records in development",()=>{vi.stubEnv("NODE_ENV","development");vi.stubEnv("DEMO_MODE","true");vi.stubEnv("DATABASE_URL","");expect(demoModeEnabled()).toBe(true);expect(demoPayments()).toHaveLength(2);vi.stubEnv("NODE_ENV","production");expect(demoModeEnabled()).toBe(false);vi.unstubAllEnvs();});});
describe("payment lifecycle",()=>{const now=new Date("2026-09-16T18:45:00Z");it("uses Asia/Kolkata dates and preserves non-date statuses",()=>{expect(paymentLifecycle.getPaymentStatus({dueDate:"2026-09-17",status:"UPCOMING"},now)).toBe("DUE_TODAY");expect(paymentLifecycle.getPaymentStatus({dueDate:"2026-09-01",status:"PAID"},now)).toBe("PAID");expect(paymentLifecycle.getPaymentStatus({dueDate:"2026-09-01",status:"PROOF_UPLOADED"},now)).toBe("PROOF_UPLOADED");expect(paymentLifecycle.getPaymentStatus({dueDate:"2026-09-01",status:"MISMATCH"},now)).toBe("MISMATCH");expect(paymentLifecycle.getPaymentStatus({dueDate:"2026-09-01",status:"VERIFIED"},now)).toBe("VERIFIED");});it("maps actions and filters/sorts action-required work",()=>{expect(paymentLifecycle.getNextAction({dueDate:"2026-09-01",status:"VERIFIED"},now)).toBe("Confirm Payment");const rows=paymentLifecycle.actionRequired([{dueDate:"2026-09-18",status:"PROOF_UPLOADED"},{dueDate:"2026-09-01",status:"UPCOMING"},{dueDate:"2026-09-18",status:"MISMATCH"}],now);expect(rows.map(r=>r.status)).toEqual(["OVERDUE","MISMATCH","PROOF_UPLOADED"]);});});
describe("reminder eligibility",()=>{const now=new Date("2026-09-16T18:45:00Z");it("uses lifecycle state and Kolkata dates",()=>{expect(reminderEligibility.getEligibleReminders({id:1,dueDate:"2026-09-20",status:"UPCOMING",email:"a@example.test"},now)[0]?.reminderType).toBe("UPCOMING_REMINDER");expect(reminderEligibility.getEligibleReminders({id:1,dueDate:"2026-09-17",status:"UPCOMING",email:"a@example.test"},now)[0]?.reminderType).toBe("DUE_TODAY_REMINDER");expect(reminderEligibility.getEligibleReminders({id:1,dueDate:"2026-09-16",status:"UPCOMING",email:"a@example.test"},now)[0]?.reminderType).toBe("OVERDUE_REMINDER");expect(reminderEligibility.getEligibleReminders({id:1,dueDate:"2026-09-01",status:"PAID",email:"a@example.test"})).toEqual([]);expect(reminderEligibility.getEligibleReminders({id:1,dueDate:"2026-09-01",status:"PROOF_UPLOADED",email:"a@example.test"})).toEqual([]);});it("never claims email delivery without configuration",async()=>{vi.stubEnv("EMAIL_PROVIDER","");vi.stubEnv("EMAIL_API_KEY","");expect(await new EmailReminderProvider().sendReminder({type:"DUE_TODAY_REMINDER",recipient:"a@example.test",client:"A",service:"S",amount:1,dueDate:"2026-01-01"})).toEqual({ok:false,code:"EMAIL_PROVIDER_NOT_CONFIGURED"});vi.unstubAllEnvs();});});
